services:
  app:
    build: .
    depends_on:
      - db
    container_name: widget-server
    restart: always
    ports:
      - 3000:3000
    environment:
      - CLOUDFLARE_ACCESS_KEY_ID=$CLOUDFLARE_ACCESS_KEY_ID
      - CLOUDFLARE_SECRET_ACCESS_KEY=$CLOUDFLARE_SECRET_ACCESS_KEY
      - CLOUDFLARE_BUCKET=$CLOUDFLARE_BUCKET
      - CLOUDFLARE_ACCOUNT_ID=$CLOUDFLARE_ACCOUNT_ID
      - CLOUDFLARE_PUBLIC_URL=$CLOUDFLARE_PUBLIC_URL
    networks:
      - widget-network
      - db-network

  db:
    image: postgres:latest
    container_name: widget-postgres
    platform: linux/amd64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=widget-server
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - widget-network

volumes:
  postgres_data:


networks:
  widget-network:
    driver: bridge
  db-network:
    driver: bridge
