name: widget-server pipe ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: AWS ECR Login
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v2

      - name: Generate tag
        id: generate_tag
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: build and push to ECR
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.ecr-login.outputs.registry }}/${{ vars.AWS_ECR_REPOSITORY }}:${{ steps.generate_tag.outputs.sha }}          

      # - name: Build and push image to AWS ECR
      #   env:
      #     AWS_ECR_REGISTRY: ${{ steps.ecr-login.outputs.registry }}
      #     AWS_ECR_REPOSITORY: ${{ vars.AWS_ECR_REPOSITORY }}
      #     IMAGE_TAG: ${{ steps.generate_tag.outputs.sha }}
      #   run: |
      #     docker build -t $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG . 
      #     docker push $AWS_ECR_REGISTRY/$AWS_ECR_REPOSITORY:$IMAGE_TAG
        

